#!/usr/bin/env ruby
require "bundler/setup"

require 'async'
require 'faraday'
require 'colorize'
require 'tty-progressbar'
require 'async/http/faraday'

require 'json'
require "kaba"

require 'dotenv'
Dotenv.load

class Application
  class << self
    def connection
      endpoint = ENV["LISA_TYPECHAT_ENDPOINT"] || "https://lisa-typechat.listenai.com"
      @connection ||= Faraday.new(endpoint) do |faraday|
        faraday.adapter :async_http, clients: Async::HTTP::Faraday::PersistentClients
        faraday.request :json
      end
    end
  end
end

# 运行 DPodfile 文件，DPodfile 是一个 Ruby 文件
load DatasetSource.podfile